export const ADVISOR_GUIDANCE = `## Advisor assistance
The ask_advisor tool is available for an independent reasoning review. The main agent remains responsible for implementation and verification.
- Handle routine, directly verifiable work yourself. Ask for a focused review when you have made two substantive attempts at the same obstacle without resolving it, when observations contradict your explanation, or when competing approaches hinge on an unresolved correctness assumption.
- Before finalizing a complex correctness review involving interacting concurrency, crash recovery, retries, idempotency, or safety/liveness requirements, call ask_advisor once for an independent review. First develop your own candidate conclusion and a concrete counterexample or evidence; do not delegate the entire task or every small step. Confidence in your own answer does not replace this review. This applies to analysis-only questions too: when no file or tool-result evidence is needed, use evidence: [].
- Preparing ask_advisor opens a LOCAL review. It does not send anything to the advisor until the human approves the exact content. You may propose this review when cloud execution requires approval; the review is where that approval is obtained. Always honor explicit user restrictions and never-ask policies.
- Submit a concise question, goal, constraints, attempted actions and observed results, and only necessary file/tool-result ranges. Do not include hidden reasoning, credentials, or whole conversation history. In Code Mode use the exposed tools.ask_advisor SDK through run_code.
- If the human denies/cancels, the advisor is unavailable, or a sent request returns unknown, continue with the available evidence and explain the remaining uncertainty. Do not automatically ask again, retry, or switch providers.
- Treat the returned advice as a hypothesis to verify. Summarize the conclusion and checks for the user; do not paste the raw tool envelope as the final answer.`

export const ADVISOR_DESCRIPTION = 'Request an independent advisor review for a difficult reasoning or correctness question. Use after repeated unsuccessful approaches, contradictory evidence, or before finalizing a complex concurrency/crash-recovery/idempotency/safety-liveness analysis. Preparing this tool only opens a local human review; each cloud request needs explicit approval. Submit concise goal, constraints, attempts and explicit evidence ranges, not hidden reasoning or full history. Advisor has no tools. After denied/cancelled/unavailable/unknown, do not automatically repeat. File evidence uses read; tool_result evidence must be a completed call in this session.'
